### ISSUE TITLE
cannot find package "bazil.org/fuse" in any of

### ISSUE THREAD

**Issue by Konstantinusz** [andreweduffy/httpfs#1]
httpfs.go:11:2: cannot find package "bazil.org/fuse" in any of:
/usr/lib/go/src/bazil.org/fuse (from $GOROOT)

**Comment by andreweduffy** [comment]
You'll probably have to do a

```
> go get -u bazil.org/fuse
```
before running this, as it assumes the bazil fuse repo's are in your GOPATH
